# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNGv_0FMen0q32n1varnkBYmtkjdRbtL
"""

from google.colab import drive
drive.mount('/content/drive')

import scipy.io
mat = scipy.io.loadmat('/content/drive/My Drive/ML assignment 3/dataset_a.mat')

mat

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

samples, label = mat['samples'], mat['labels']
df = pd.DataFrame(list(samples))
label = pd.DataFrame(label[0])
df['label'] = label

df.head()

x=df[0]
y=df[1]
z=df['label']

data = pd.DataFrame({"X_Value": x, "Y_Value": y, "Category": z})

plt.figure(figsize=(15,10))
sns.scatterplot(data=data, x="X_Value", y="Y_Value", hue="Category",palette="bright")

